#pragma once
#include "Global.h"
#include "clsDate.h"
#include "clsDB.h"
#include "sqlite3.h"
#include <vector>
#include <string>

using namespace std;

class clsSystemAnnouncement
{
private:
    enum enMode { EmptyMode = 0, AddMode = 1, UpdateMode = 2 };

    enMode _Mode;
    int _ID;
    string _Title;
    string _Message;
    string _TargetAudience;
    string _Date;

    // --- DB HELPERS ---
    static string _EscapeQuotes(const string& s)
    {
        string r; r.reserve(s.size());
        for (char c : s) {
            if (c == '\'') r += "''"; else r += c;
        }
        return r;
    }

    static clsSystemAnnouncement _ConvertRowToObj(sqlite3_stmt* stmt)
    {
        int id = sqlite3_column_int(stmt, 0);
        string t = (const char*)sqlite3_column_text(stmt, 1);
        string m = (const char*)sqlite3_column_text(stmt, 2);
        string ta = (const char*)sqlite3_column_text(stmt, 3);
        string d = (const char*)sqlite3_column_text(stmt, 4);

        return clsSystemAnnouncement(UpdateMode, id, t, m, ta, d);
    }

    void _Add()
    {
        sqlite3* db = clsDB::OpenDB("University.db");
        if (!db) return;

        string sql = "INSERT INTO SystemAnnouncements (Title, Message, TargetAudience, Date) VALUES ('" +
            _EscapeQuotes(_Title) + "', '" + _EscapeQuotes(_Message) + "', '" + _EscapeQuotes(_TargetAudience) + "', '" + _Date + "');";

        clsDB::Execute(db, sql);

        // Get the ID generated by DB
        _ID = (int)sqlite3_last_insert_rowid(db);

        clsDB::CloseDB(db);
    }

    void _Update()
    {
        sqlite3* db = clsDB::OpenDB("University.db");
        if (!db) return;

        string sql = "UPDATE SystemAnnouncements SET "
            "Title='" + _EscapeQuotes(_Title) + "', "
            "Message='" + _EscapeQuotes(_Message) + "', "
            "TargetAudience='" + _EscapeQuotes(_TargetAudience) + "' "
            "WHERE ID=" + to_string(_ID) + ";";

        clsDB::Execute(db, sql);
        clsDB::CloseDB(db);
    }

public:

    // Constructors
    clsSystemAnnouncement(enMode Mode, int ID, string Title, string Msg, string Target, string Date)
    {
        _Mode = Mode;
        _ID = ID;
        _Title = Title;
        _Message = Msg;
        _TargetAudience = Target;
        _Date = Date;
    }

    // Default Constructor (for Add Mode)
    clsSystemAnnouncement(string Title, string Msg, string Target)
    {
        _Mode = AddMode;
        _ID = -1;
        _Title = Title;
        _Message = Msg;
        _TargetAudience = Target;
        _Date = clsDate::GetSystemDateTimeString();
    }

    // Empty Constructor
    clsSystemAnnouncement() { _Mode = EmptyMode; _ID = -1; }

    // Properties
    int ID() { return _ID; }
    string Title() { return _Title; }
    string Message() { return _Message; }
    string TargetAudience() { return _TargetAudience; }
    string Date() { return _Date; }

    void SetTitle(string s) { _Title = s; }
    void SetMessage(string s) { _Message = s; }
    void SetTarget(string s) { _TargetAudience = s; }

    bool IsEmpty() { return _Mode == EmptyMode; }

    // --- PUBLIC FUNCTIONS ---

    // 1. Find by ID (For Update/Delete)
    static clsSystemAnnouncement Find(int ID)
    {
        sqlite3* db = clsDB::OpenDB("University.db");
        if (!db) return clsSystemAnnouncement();

        string sql = "SELECT * FROM SystemAnnouncements WHERE ID=" + to_string(ID) + ";";
        sqlite3_stmt* stmt;

        clsSystemAnnouncement obj; // Empty by default

        if (sqlite3_prepare_v2(db, sql.c_str(), -1, &stmt, nullptr) == SQLITE_OK)
        {
            if (sqlite3_step(stmt) == SQLITE_ROW) {
                obj = _ConvertRowToObj(stmt);
            }
        }
        sqlite3_finalize(stmt);
        clsDB::CloseDB(db);
        return obj;
    }

    // 2. Check Duplicate Title
    static bool IsTitleExist(string Title)
    {
        sqlite3* db = clsDB::OpenDB("University.db");
        if (!db) return false;

        string sql = "SELECT 1 FROM SystemAnnouncements WHERE Title='" + _EscapeQuotes(Title) + "';";
        sqlite3_stmt* stmt;
        bool exists = false;

        if (sqlite3_prepare_v2(db, sql.c_str(), -1, &stmt, nullptr) == SQLITE_OK)
        {
            if (sqlite3_step(stmt) == SQLITE_ROW) exists = true;
        }
        sqlite3_finalize(stmt);
        clsDB::CloseDB(db);
        return exists;
    }

    // 3. Save (Add or Update)
    bool Save()
    {
        if (_Mode == EmptyMode) return false;

        if (_Mode == AddMode) {
            _Add();
            _Mode = UpdateMode;
            return true;
        }
        else if (_Mode == UpdateMode) {
            _Update();
            return true;
        }
        return false;
    }

    // 4. Delete
    bool Delete()
    {
        sqlite3* db = clsDB::OpenDB("University.db");
        if (!db) return false;

        string sql = "DELETE FROM SystemAnnouncements WHERE ID=" + to_string(_ID) + ";";
        clsDB::Execute(db, sql);
        clsDB::CloseDB(db);
        return true;
    }

    // 5. Get List
    static vector<clsSystemAnnouncement> GetListFor(string ViewerRole)
    {
        vector<clsSystemAnnouncement> list;
        sqlite3* db = clsDB::OpenDB("University.db");
        if (!db) return list;

        string sql;
        if (ViewerRole == "Admin") // Admin sees everything
            sql = "SELECT * FROM SystemAnnouncements;";
        else
            sql = "SELECT * FROM SystemAnnouncements WHERE TargetAudience = 'All' OR TargetAudience = '" + ViewerRole + "';";

        sqlite3_stmt* stmt;
        if (sqlite3_prepare_v2(db, sql.c_str(), -1, &stmt, nullptr) == SQLITE_OK)
        {
            while (sqlite3_step(stmt) == SQLITE_ROW)
            {
                list.push_back(_ConvertRowToObj(stmt));
            }
        }
        sqlite3_finalize(stmt);
        clsDB::CloseDB(db);
        return list;
    }
};